language: bash

os:
  - linux
  - osx
sudo: required
before_install:
  - ./travis-install.sh

script:
  - bash --version
  - ./all-tests.sh bash
  - zsh --version
  - ./all-tests.sh zsh

notifications:
    email: false
